### ISSUE TITLE
0.2.0 Checklist

### ISSUE THREAD

**Issue by aravindhebbali** [rsquaredacademy/blorr#75]
Prepare for release:

* [ ] `devtools::check_win_devel()`
* [ ] `rhub::check_for_cran()`
* [ ] [Polish NEWS](http://style.tidyverse.org/news.html#before-release)

Perform release:

* [ ] Bump version (in DESCRIPTION and NEWS)
* [ ] `devtools::check_win_devel()` (again!)
* [ ] `devtools::submit_cran()`
* [ ] `pkgdown::build_site()`
* [ ] Approve email

Wait for CRAN...

* [ ] Tag release
* [ ] Bump dev version
* [ ] Write blog post
* [ ] Tweet
* [ ] Add link to blog post in pkgdown news menu

Template from <https://github.com/r-lib/usethis/issues/338>
